### ISSUE TITLE
Show syntax errors in your code

### ISSUE THREAD

**Issue by bernhard-42** [roipoussiere/cadquery-vscode#1]
Typos, wrong API use, ... will just be hidden behind the cadquery server.
Can this be surfaced in some VS Code output model?

**Comment by lypwig** [comment]
Yes, good point!

Currently the server returns a json response that only contains the `model` field at the root level, and I plan to add `stdout` and `stderr`.

**Comment by lypwig** [comment]
I added type checking and code completion! It will be included in the next release.

![pylance](https://user-images.githubusercontent.com/1665542/161253031-2e917443-3d9c-42fe-884f-0d29820cc57e.png)

Note that I'm still on my host, where CadQuery is not installed.

It is made using CadQuery stubs generated with MyPy, that I included in the extension.

Here it works with Pylance, but it should work with other language servers.

**Comment by lypwig** [comment]
I think I can close this now, since it fixes the original request *Show syntax errors in your code*. I will add code output in the future.
