### ISSUE TITLE
Bug in Orientation or Wrong views?

### ISSUE THREAD

**Issue by snapo** [roipoussiere/cadquery-vscode#10]
Hi ,
first i am very new to CAD so excuse my bug report if i made something wrong....

```
import cadquery as cq

res = cq.Workplane("front").box(50, 50, 50)

res = res + cq.Workplane("front").text("Front", 8, 26)
res = res + cq.Workplane("back").text("Back", 8, 26)
res = res + cq.Workplane("top").text("Top", 8, 26)
res = res + cq.Workplane("bottom").text("Bottom", 8, 26)
res = res + cq.Workplane("left").text("Left", 8, 26)
res = res + cq.Workplane("right").text("Right", 8, 26)

res = res.rotate((0, 0, 0), (1, 0, 0), 90) # Rotates the object 90 degree down so it works without touching in Cura Slicer and Super Slicer
cq.exporters.export(res, "test.step")
cq.exporters.export(res, "test.stl")
res = res.rotate((0, 0, 0), (1, 0, 180), 90)
show(res)
```

The rotate before exporting step and stl is required so it is aligned with 3d printer slicers.

The rotate before the show is required so i dont have to use the mouse to view to click on it.... so it looks good...

This puts everything in a good perspective....
![image](https://user-images.githubusercontent.com/6347922/177683448-86e0fe00-1bda-4988-9392-a3d0bd62c598.png)

**The only problem is the LEFT/RIGHT are opposing....** (TOP, BOTTOM, FRONT, BACK are working correctly)
![image](https://user-images.githubusercontent.com/6347922/177683945-018b45e1-9583-45ea-8491-0847771cf372.png)

**Comment by snapo** [comment]
Closing it because cq chat is not welcoming VSCode users.... was fun to try

**Comment by lypwig** [comment]
Sorry for the delay. Discussion on this issue continues here: https://github.com/bernhard-42/jupyter-cadquery/issues/90
