### ISSUE TITLE
Code completion is failed when adding more than two dots.

### ISSUE THREAD

**Issue by pbjacob** [roipoussiere/cadquery-vscode#14]
For example, when I type:
`obj = cq.Workplane('front').box(1,2,3)`
the code completion works well. But when adding more dots, such as :
`obj = cq.Workplane('front').box(1,2,3).faces('>Z').workplane().hole(0.2)`
all the following up methods can not activate code completion.

I am using VSCode v1.71.1 on Windows 10 1809 LTSC, and this plugin is of version 0.1.3 which is the latest.

By the way, I only use this plugin as a CADQuery code completion plugin in VSCode for easily writing .py file. The 3D object is simutaniously being rendered in CQ-Editor by Autoreload function.

**Comment by pbjacob** [comment]
Apologies for this post, because after reinstalling VSCode on my PC, this plugin works now.
Thanks for your work any way.

**Comment by lypwig** [comment]
You don't have to apologies for reporting a bug, thank you.

So you think it was related to a bad installation of VSCode?
