### ISSUE TITLE
Make cq-server port configurable

### ISSUE THREAD

**Issue by bernhard-42** [roipoussiere/cadquery-vscode#4]
On a Mac port 5000 is used and I don't want to turn the respective service off.
And sometimes I'd like to also control the host variable. `0.0.0.0` is pretty broad.
So support for `cq-server --host 0.0.0.0 --port 4999` or `cq-server -h 0.0.0.0 -p 4999` would be highly appreciated.

**Comment by lypwig** [comment]
Thanks!

It is now included in v0.1.2 of [cadquery-server](https://pypi.org/project/cadquery-server/).

**Comment by bernhard-42** [comment]
works fine for me, thx
