### ISSUE TITLE
Allow reopening the CAD view

### ISSUE THREAD

**Issue by bernhard-42** [roipoussiere/cadquery-vscode#7]
After closing the VS Code tab with the CAD view, one cannot open it again. An error appears:

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/954408/161421413-89130e90-509b-4dbe-a45f-da52f7d6a6d3.png">

**Comment by lypwig** [comment]
It should be fixed in the last release (v0.1.2), could you give a try?

**Comment by bernhard-42** [comment]
yep, works fine for me now, thanks
