### ISSUE TITLE
Refresh when VS Code tab is moved

### ISSUE THREAD

**Issue by bernhard-42** [roipoussiere/cadquery-vscode#8]
Before

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/954408/161421500-0c3783f8-4c1b-4f62-9814-1770cf6d7bec.png">

Then I move the CAD tab:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/954408/161421523-93d3ffb7-2dfd-44ab-9f1e-b95574e17797.png">

So the bottom view is empty now
If I save again, it appears:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/954408/161421574-0f615d68-ff12-459c-9ee9-a0125681bd3c.png">

While the cad adapts to the size of the tab, the objects camera view is sub optimal. Maybe you could reset the camera?
Can be done by calling `viewer.reset()`.

**Comment by bernhard-42** [comment]
ah, nope. `reset` doesn't help. 
This is a bug in three-cad-viewer. I did only test it with `width:height` ratios of about 4:3 ...
See https://github.com/bernhard-42/three-cad-viewer/issues/5

**Comment by bernhard-42** [comment]
@roipoussiere v1.5.9 fixes it. Now wide cad view with low height are supported as initial zoom and for `viewer.reset()`

**Comment by lypwig** [comment]
The last version is based on three-cad-viewer v1.5.9.

I still need to update the viewer size according to the panel size, but the camera seems good.

**Comment by bernhard-42** [comment]
yes, works now
