### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by Jojain** [roipoussiere/cadquery-vscode#9]
Hello, I've tried your extension on Windows and when I want to open the viewer I get this error msg :
`Une erreur système s'est produite (ENOENT: no such file or directory, open '/c:/Users/Romain/.vscode/extensions/roipoussiere.cadquery-0.1.2/static/cq-viewer.html')`

The problem is due to the first slash before the c:/, the file is actually in the right location, the path is just corrupted due to the linux slash used here.

**Comment by lypwig** [comment]
Fixed in new release 0.1.3 (874f705798deb28393a2e23aaa97547646ec7382)
